/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as manager from "./manager";
export type { manager };
export type { Ownable } from "./Ownable";
