// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { IUniswapV2Factory$Type } from "./IUniswapV2Factory";
import { IUniswapV2Pair$Type } from "./IUniswapV2Pair";
import { IUniswapV2Router01$Type } from "./IUniswapV2Router01";
import { IUniswapV2Router02$Type } from "./IUniswapV2Router02";
import { IWETH$Type } from "./IWETH";
import { SafeMath$Type } from "./SafeMath";
import { SwapRouter$Type } from "./SwapRouter";
import { TransferHelper$Type } from "./TransferHelper";
import { UniswapV2Library$Type } from "./UniswapV2Library";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["IUniswapV2Factory"]: IUniswapV2Factory$Type;
    ["IUniswapV2Pair"]: IUniswapV2Pair$Type;
    ["IUniswapV2Router01"]: IUniswapV2Router01$Type;
    ["IUniswapV2Router02"]: IUniswapV2Router02$Type;
    ["IWETH"]: IWETH$Type;
    ["SafeMath"]: SafeMath$Type;
    ["SwapRouter"]: SwapRouter$Type;
    ["TransferHelper"]: TransferHelper$Type;
    ["UniswapV2Library"]: UniswapV2Library$Type;
    ["contracts/SwapRouter.sol:IERC20"]: IERC20$Type;
    ["contracts/SwapRouter.sol:IUniswapV2Factory"]: IUniswapV2Factory$Type;
    ["contracts/SwapRouter.sol:IUniswapV2Pair"]: IUniswapV2Pair$Type;
    ["contracts/SwapRouter.sol:IUniswapV2Router01"]: IUniswapV2Router01$Type;
    ["contracts/SwapRouter.sol:IUniswapV2Router02"]: IUniswapV2Router02$Type;
    ["contracts/SwapRouter.sol:IWETH"]: IWETH$Type;
    ["contracts/SwapRouter.sol:SafeMath"]: SafeMath$Type;
    ["contracts/SwapRouter.sol:SwapRouter"]: SwapRouter$Type;
    ["contracts/SwapRouter.sol:TransferHelper"]: TransferHelper$Type;
    ["contracts/SwapRouter.sol:UniswapV2Library"]: UniswapV2Library$Type;
  }
}
