// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TransferHelper$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TransferHelper",
  "sourceName": "contracts/SwapRouter.sol",
  "abi": [],
  "bytecode": "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a1247fd7353982f1ba4b73c88a431b6120f8e7f737d50f6cd68bc439bffbef3064736f6c63430006060033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a1247fd7353982f1ba4b73c88a431b6120f8e7f737d50f6cd68bc439bffbef3064736f6c63430006060033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TransferHelper",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/SwapRouter.sol:TransferHelper",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TransferHelper",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransferHelper$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/SwapRouter.sol:TransferHelper",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransferHelper$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TransferHelper",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/SwapRouter.sol:TransferHelper",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
}
