// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { IUniswapV2Callee$Type } from "./IUniswapV2Callee";
import { IUniswapV2ERC20$Type } from "./IUniswapV2ERC20";
import { IUniswapV2Factory$Type } from "./IUniswapV2Factory";
import { IUniswapV2Pair$Type } from "./IUniswapV2Pair";
import { Math$Type } from "./Math";
import { SafeMath$Type } from "./SafeMath";
import { UQ112x112$Type } from "./UQ112x112";
import { UniswapV2ERC20$Type } from "./UniswapV2ERC20";
import { UniswapV2Factory$Type } from "./UniswapV2Factory";
import { UniswapV2Pair$Type } from "./UniswapV2Pair";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["IUniswapV2Callee"]: IUniswapV2Callee$Type;
    ["IUniswapV2ERC20"]: IUniswapV2ERC20$Type;
    ["IUniswapV2Factory"]: IUniswapV2Factory$Type;
    ["IUniswapV2Pair"]: IUniswapV2Pair$Type;
    ["Math"]: Math$Type;
    ["SafeMath"]: SafeMath$Type;
    ["UQ112x112"]: UQ112x112$Type;
    ["UniswapV2ERC20"]: UniswapV2ERC20$Type;
    ["UniswapV2Factory"]: UniswapV2Factory$Type;
    ["UniswapV2Pair"]: UniswapV2Pair$Type;
    ["contracts/SwapCore.sol:IERC20"]: IERC20$Type;
    ["contracts/SwapCore.sol:IUniswapV2Callee"]: IUniswapV2Callee$Type;
    ["contracts/SwapCore.sol:IUniswapV2ERC20"]: IUniswapV2ERC20$Type;
    ["contracts/SwapCore.sol:IUniswapV2Factory"]: IUniswapV2Factory$Type;
    ["contracts/SwapCore.sol:IUniswapV2Pair"]: IUniswapV2Pair$Type;
    ["contracts/SwapCore.sol:Math"]: Math$Type;
    ["contracts/SwapCore.sol:SafeMath"]: SafeMath$Type;
    ["contracts/SwapCore.sol:UQ112x112"]: UQ112x112$Type;
    ["contracts/SwapCore.sol:UniswapV2ERC20"]: UniswapV2ERC20$Type;
    ["contracts/SwapCore.sol:UniswapV2Factory"]: UniswapV2Factory$Type;
    ["contracts/SwapCore.sol:UniswapV2Pair"]: UniswapV2Pair$Type;
  }
}
