// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeMath$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeMath",
  "sourceName": "contracts/SwapCore.sol",
  "abi": [],
  "bytecode": "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158200c312e06ffde65792431f68bd1eaee5f57823cc5712f1100b9c8b2940f0b1a7564736f6c63430005100032",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158200c312e06ffde65792431f68bd1eaee5f57823cc5712f1100b9c8b2940f0b1a7564736f6c63430005100032",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/SwapCore.sol:SafeMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeMath$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/SwapCore.sol:SafeMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/SwapCore.sol:SafeMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeMath$Type["abi"]>>;
}
