// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface UQ112x112$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "UQ112x112",
  "sourceName": "contracts/SwapCore.sol",
  "abi": [],
  "bytecode": "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820ad0584231bb92596912305f87d7f4979aaa94b25effa50fd9bb3089bf6309d5a64736f6c63430005100032",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820ad0584231bb92596912305f87d7f4979aaa94b25effa50fd9bb3089bf6309d5a64736f6c63430005100032",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "UQ112x112",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UQ112x112$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/SwapCore.sol:UQ112x112",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UQ112x112$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "UQ112x112",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UQ112x112$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/SwapCore.sol:UQ112x112",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UQ112x112$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "UQ112x112",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UQ112x112$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/SwapCore.sol:UQ112x112",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UQ112x112$Type["abi"]>>;
}
