/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PetInterface extends Interface {
  getFunction(
    nameOrSignature: "increaseExp" | "increaseLevel" | "resetPet" | "setHp"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "increaseExp",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetPet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHp",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "increaseExp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetPet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHp", data: BytesLike): Result;
}

export interface Pet extends BaseContract {
  connect(runner?: ContractRunner | null): Pet;
  waitForDeployment(): Promise<this>;

  interface: PetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  increaseExp: TypedContractMethod<
    [tokenId: BigNumberish, exp: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseLevel: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetPet: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  setHp: TypedContractMethod<
    [tokenId: BigNumberish, hp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "increaseExp"
  ): TypedContractMethod<
    [tokenId: BigNumberish, exp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseLevel"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetPet"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHp"
  ): TypedContractMethod<
    [tokenId: BigNumberish, hp: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
