/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Pet, PetInterface } from "../../../contracts/game/Pet";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exp",
        type: "uint256",
      },
    ],
    name: "increaseExp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "increaseLevel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "resetPet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "hp",
        type: "uint256",
      },
    ],
    name: "setHp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d4806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063117c909114610051578063412071051461006d5780638fa17f3714610089578063c429a773146100a5575b600080fd5b61006b600480360381019061006691906101ce565b6100c1565b005b610087600480360381019061008291906101ce565b610115565b005b6100a3600480360381019061009e91906101fb565b610145565b005b6100bf60048036038101906100ba91906101fb565b610163565b005b60405180606001604052806000815260200160008152602001606481525060008083815260200190815260200160002060008201518160000155602082015181600101556040820151816002015590505050565b6001600080838152602001908152602001600020600001600082825461013b919061026a565b9250508190555050565b80600080848152602001908152602001600020600201819055505050565b806000808481526020019081526020016000206001016000828254610188919061026a565b925050819055505050565b600080fd5b6000819050919050565b6101ab81610198565b81146101b657600080fd5b50565b6000813590506101c8816101a2565b92915050565b6000602082840312156101e4576101e3610193565b5b60006101f2848285016101b9565b91505092915050565b6000806040838503121561021257610211610193565b5b6000610220858286016101b9565b9250506020610231858286016101b9565b9150509250929050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600061027582610198565b915061028083610198565b92508282019050808211156102985761029761023b565b5b9291505056fea26469706673582212208296a648d709ce65169a2d78eefed15984921a868e1e295f1333ee2d45558b1a64736f6c63430008140033";

type PetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Pet__factory extends ContractFactory {
  constructor(...args: PetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Pet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Pet__factory {
    return super.connect(runner) as Pet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PetInterface {
    return new Interface(_abi) as PetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Pet {
    return new Contract(address, _abi, runner) as unknown as Pet;
  }
}
