/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Rebasing,
  IERC20RebasingInterface,
} from "../../../contracts/blast/IERC20Rebasing";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum YieldMode",
        name: "",
        type: "uint8",
      },
    ],
    name: "configure",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getClaimableAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC20Rebasing__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20RebasingInterface {
    return new Interface(_abi) as IERC20RebasingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Rebasing {
    return new Contract(address, _abi, runner) as unknown as IERC20Rebasing;
  }
}
