/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swapCoreSol from "./SwapCore.sol";
export type { swapCoreSol };
import type * as swapRouterSol from "./SwapRouter.sol";
export type { swapRouterSol };
export type { TokenErc20 } from "./TokenErc20";
export type { WETH9 } from "./WETH9";
